import { library } from '@fortawesome/fontawesome-svg-core';
import { 
    faAngleUp,
    faAngleDown,
    faComments,
    faEnvelope, 
    faGripHorizontal, 
    faPlusSquare,
    faSearch,
    faQuestionCircle,
    faUserCircle, 
    faWrench,
    faCheckCircle,
    faCheckDouble,
    faHourglassStart,
    faSquare,
    faTimes,
    faTimesCircle,
    faCheckSquare
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faAngleUp,
  faAngleDown,
  faEnvelope, 
  faGripHorizontal, 
  faPlusSquare, 
  faCheckSquare,
  faSquare,
  faUserCircle,
  faWrench,
  faCheckDouble,
  faHourglassStart,
  faTimes,
  faTimesCircle,
  faComments,
  faSearch,
  faQuestionCircle,
  faCheckCircle,
);